spring:
  application:
    name: crbook-eureka
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    fetch-registry: false    #要不要去注册中心获取其他服务的地址 , 解决eureka启动时报错
    register-with-eureka: false    #是否当前客户端要注册到eureka