spring:
  application:
    name: crbook-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hcl0923/512zuul  #配置文件所在仓库
          default-label: master    #配置文件分支
          search-paths: config  #配置文件所在根目录

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
